version: 2
jobs:
  build:
    docker:
      - image: eriktim/docker-elm-ci

    steps:
      - checkout

      - run:
          name: Build Elm
          command: elm make

      - run:
          name: Run Tests
          command: elm-test
